package:
  name: graphvampnets
  version: 1.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  host:
    - pip
    - python 
    - numpy 
  run:
    - python
    - setuptools
    - scikit-learn >0.21.1
    - jinja2 <3.1
    - scipy
    - pytorch
    - torchvision
    - matplotlib
    - jupyter
    - pyg